language: objective-c
osx_image: xcode9
xcode_project: DVR.xcodeproj

matrix:
  include:
    - xcode_scheme: DVR-iOS
      xcode_sdk: iphonesimulator
      env:
        - DESTINATION="iOS Simulator,OS=11.0,name=iPhone 7 Plus"
    - xcode_scheme: DVR-OSX
      xcode_sdk: macosx
      env:
        - DESTINATION="OS X"
    - env:
      - SWIFT_BUILD=true

script: 
  - ./Scripts/travis-build-test.sh

